#!/usr/bin/env node
/**
 * Auto-generates packages/security/src/index.ts from filesystem module list.
 * Run: node --experimental-strip-types packages/security/scripts/generate-index.ts
 */

import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.resolve(__dirname, "../src")
const outFile = path.join(srcDir, "index.ts")

/** Modules excluded from the barrel (side effects or self-reference). */
const EXCLUDE = new Set(["index.ts", "mcp_server.ts"])

/** Platform modules also exported flat for direct class/function imports. */
const PLATFORM_FLAT = new Set([
  "attack_surface.ts",
  "finding_lifecycle.ts",
  "validation_planner.ts",
  "validation_engine.ts",
  "tool_broker.ts",
  "sandbox_runner.ts",
  "policy_daemon.ts",
  "capability_policy.ts",
  "context_guard.ts",
  "parameter_analyzer.ts",
  "app_security_engine.ts",
  "impact_engine.ts",
  "live_web_exploit.ts",
  "live_cred_attacks.ts",
  "live_privesc.ts",
  "live_scanner.ts",
  "live_postex.ts",
  "live_ad_attacks.ts",
  "live_recon.ts",
  "msf_client.ts",
  "web_exploit.ts",
  "privesc.ts",
  "lateral.ts",
  "toolkit.ts",
  "c2_platform.ts",
  "cloud.ts",
  "evasion.ts",
  "ad_engine.ts",
  "runtime_exec.ts",
])

const files = fs
  .readdirSync(srcDir)
  .filter((f) => f.endsWith(".ts") && !EXCLUDE.has(f))
  .sort()

const aresDir = path.join(srcDir, "ares")
const aresFiles = fs.existsSync(aresDir)
  ? fs.readdirSync(aresDir).filter((f) => f.endsWith(".ts") && !f.includes("test")).sort()
  : []

const lines: string[] = [
  "/**",
  " * @module security",
  " * OurMine Security Engine Master Index",
  " * AUTO-GENERATED by packages/security/scripts/generate-index.ts — do not edit manually.",
  " */",
  "",
  "// ─── Platform modules (flat exports for direct class/function access) ───",
  "",
]

for (const f of files.filter((f) => PLATFORM_FLAT.has(f))) {
  lines.push(`export * from './${f}'`)
}

lines.push("")
lines.push("// ─── ARES module namespaces (CLI / MCP / REPL: security.<module>.<fn>) ───")
lines.push("")

for (const f of files) {
  const name = f.replace(/\.ts$/, "")
  lines.push(`export * as ${name} from './${f}'`)
}

if (aresFiles.length > 0) {
  lines.push("")
  lines.push("// ─── ARES Syndicate modules (security.ares.<module>.<fn>) ───")
  lines.push("")
  for (const f of aresFiles) {
    const name = f.replace(/\.ts$/, "").replace(/[^a-zA-Z0-9_]/g, "_")
    lines.push(`export * as ares_${name} from './ares/${f}'`)
  }
}

lines.push("")
fs.writeFileSync(outFile, lines.join("\n"))
console.log(`Generated ${outFile} with ${files.length} module namespaces (${PLATFORM_FLAT.size} flat exports)`)
