/**
 * @module engagement_report
 * Markdown engagement summary export from unified engagement graph.
 */
import * as fs from "node:fs"
import * as path from "node:path"
import type { EngagementGraph } from "./engagement_graph.ts"
import type { ActionablePlan } from "./pentest_plan_builder.ts"
import { ensureAresDir } from "./ares/_base.ts"
import { writeArtifact } from "./mcp_artifacts.ts"

export interface EngagementReport {
  target: string
  objective: string
  persona: string
  generatedAt: string
  markdown: string
  markdownPath: string
  summary: string
  artifactId?: string
}

function section(title: string, lines: string[]): string {
  if (!lines.length) return ""
  return `## ${title}\n\n${lines.join("\n")}\n\n`
}

/** Build markdown engagement report from graph state. */
export function buildEngagementMarkdown(
  eg: EngagementGraph,
  opts: { plan?: ActionablePlan; blockers?: string[]; phasesCompleted?: string[] } = {},
): string {
  const lines: string[] = [
    `# Engagement Report: ${eg.target}`,
    "",
    `- **Objective:** ${eg.objective}`,
    `- **Persona:** ${eg.persona}`,
    `- **Generated:** ${new Date().toISOString()}`,
  ]
  if (opts.phasesCompleted?.length) {
    lines.push(`- **Phases completed:** ${opts.phasesCompleted.join(" → ")}`)
  }
  lines.push("")

  const confirmed = eg.confirmed.map((c) =>
    `- [${c.kind}] **${c.label}**${c.detail ? ` — ${c.detail}` : ""}${c.severity ? ` (${c.severity})` : ""}`,
  )
  const candidates = eg.candidates.map((c) =>
    `- [${c.kind}] ${c.label}${c.detail ? ` — ${c.detail}` : ""}`,
  )
  const blockers = (opts.blockers ?? eg.blockers).map((b) => `- ${b}`)
  const otHosts = eg.otHosts.map((h) =>
    `- ${h.host}: ${h.protocols.join(",") || "unknown"} ports=[${h.openPorts.join(",")}]`,
  )

  lines.push(section("Confirmed Findings", confirmed))
  lines.push(section("Candidates", candidates))
  lines.push(section("Blockers", blockers))
  lines.push(section("OT Hosts", otHosts))

  if (opts.plan?.nextActions.length) {
    const actions = opts.plan.nextActions.map((a) =>
      `${a.step}. **${a.label}** (\`${a.tool}\`) — ${a.rationale}`,
    )
    lines.push(section("Recommended Next Actions", actions))
  }

  if (eg.pivotScores?.length) {
    const pivots = eg.pivotScores.map((p) =>
      `- ${p.subnet} (conf=${p.confidence}): ${p.reason}`,
    )
    lines.push(section("Pivot Scores", pivots))
  }

  lines.push("---\n*Generated by OurMine engagement_report — cryptographic proof via ares_proof_export*")
  return lines.filter(Boolean).join("\n")
}

/** Write markdown report to disk and return paths. */
export function exportEngagementReport(
  eg: EngagementGraph,
  opts: {
    plan?: ActionablePlan
    blockers?: string[]
    phasesCompleted?: string[]
    outDir?: string
  } = {},
): EngagementReport {
  const markdown = buildEngagementMarkdown(eg, opts)
  const outDir = opts.outDir ?? ensureAresDir("reports")
  fs.mkdirSync(outDir, { recursive: true })
  const safeTarget = eg.target.replace(/[^a-zA-Z0-9._-]/g, "_")
  const markdownPath = path.join(outDir, `engagement_${safeTarget}_${Date.now()}.md`)
  fs.writeFileSync(markdownPath, markdown)

  const summary = `${eg.confirmed.length} confirmed, ${eg.candidates.length} candidates, ${eg.blockers.length} blocker(s)`
  const artifactId = writeArtifact("engagement_report", {
    target: eg.target,
    objective: eg.objective,
    persona: eg.persona,
    markdownPath,
    confirmedCount: eg.confirmed.length,
    candidateCount: eg.candidates.length,
    summary,
  })

  return {
    target: eg.target,
    objective: eg.objective,
    persona: eg.persona,
    generatedAt: new Date().toISOString(),
    markdown,
    markdownPath,
    summary,
    artifactId,
  }
}

export default { buildEngagementMarkdown, exportEngagementReport }
