/**
 * @module proof_report
 * HTML evidence report from proof pack (print-to-PDF ready).
 */
import * as fs from "node:fs"
import * as path from "node:path"
import type { ProofPack } from "./proof_pack.ts"

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

export function renderHtmlReport(pack: ProofPack): string {
  const findings = pack.findings
  const cov = pack.coverage
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>OurMine Proof Pack — ${esc(pack.target)}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 960px; margin: 2rem auto; color: #111; }
  h1 { color: #c0392b; border-bottom: 2px solid #c0392b; padding-bottom: 0.5rem; }
  .meta { color: #666; font-size: 0.9rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #ddd; padding: 0.5rem; text-align: left; }
  th { background: #f5f5f5; }
  .sev-critical { color: #c0392b; font-weight: bold; }
  .sev-high { color: #e67e22; font-weight: bold; }
  .sev-medium { color: #f39c12; }
  .merkle { font-family: monospace; font-size: 0.75rem; word-break: break-all; background: #f9f9f9; padding: 0.5rem; }
  @media print { body { margin: 1cm; } }
</style>
</head>
<body>
<h1>OurMine Engagement Proof Pack</h1>
<p class="meta">Target: <strong>${esc(pack.target)}</strong> | Generated: ${esc(pack.generatedAt)} | Version ${pack.version}</p>

<h2>Executive Summary</h2>
<ul>
  <li>Assets: ${pack.graphSummary.assets ?? 0}</li>
  <li>Services: ${pack.graphSummary.services ?? 0}</li>
  <li>Findings: ${findings.length}</li>
  <li>Credentials harvested: ${pack.credentials.count}</li>
  <li>ATT&CK coverage: ${cov.percent}% (${cov.covered}/${cov.total})</li>
</ul>

<h2>Evidence Chain</h2>
<p class="merkle">Merkle root: ${esc(pack.merkleRoot)}</p>
<p>${pack.chain.length} chained evidence entries</p>

<h2>Findings</h2>
<table>
<tr><th>Title</th><th>Severity</th><th>State</th><th>Technique</th></tr>
${findings.map((f) => `<tr><td>${esc(f.title)}</td><td class="sev-${esc(f.severity)}">${esc(f.severity)}</td><td>${esc(f.state)}</td><td>${esc(f.technique ?? "")}</td></tr>`).join("\n")}
</table>

<h2>ATT&CK Navigator Layer</h2>
<p>${pack.attackNavigator.techniques.length} techniques mapped</p>
<ul>
${pack.attackNavigator.techniques.slice(0, 30).map((t) => `<li>${esc(t.techniqueID)} — ${esc(t.comment)}</li>`).join("\n")}
</ul>

<h2>Missing Profile Techniques</h2>
<ul>
${(cov.missing ?? []).slice(0, 20).map((t) => `<li>${esc(t)}</li>`).join("\n")}
</ul>

<footer><p class="meta">Generated by OurMine ARES — evidence-first offensive security</p></footer>
</body>
</html>`
}

export function writeHtmlReport(pack: ProofPack, outDir = path.join(process.cwd(), ".ourmine", "proof")): string {
  fs.mkdirSync(outDir, { recursive: true })
  const file = path.join(outDir, `report_${pack.target.replace(/[^a-zA-Z0-9._-]/g, "_")}_${Date.now()}.html`)
  fs.writeFileSync(file, renderHtmlReport(pack))
  return file
}

export default { renderHtmlReport, writeHtmlReport }
