/**
 * Steganography C2 — covert command channels via real pixel-level LSB
 * embedding in 24-bit BMP carriers. Pure Node — no image libraries needed.
 *
 * Port of `modules.stego_c2`. All operations are local (file bytes).
 * Seeded noise ensures deterministic carriers for testable round-trips.
 */



// ------------------------------------------------------------------------- //
// LSB embed/extract (pure bytes — work on raw pixel data)
// ------------------------------------------------------------------------- //

/** Embed payload bytes into carrier pixel data using LSB substitution.
 *  Length-prefixed (4-byte big-endian uint32). */
export function embedImageLsb(carrier: Uint8Array, payload: Uint8Array): Uint8Array {
  const lenBuf = Buffer.alloc(4);
  lenBuf.writeUInt32BE(payload.length, 0);
  const allBits = bitsFromBytes(Buffer.concat([lenBuf, payload]));

  if (allBits.length > carrier.length * 8) {
    throw new Error(`Payload too large for carrier: need ${allBits.length} bits, have ${carrier.length * 8}`);
  }

  const out = new Uint8Array(carrier);
  for (let i = 0; i < allBits.length && i < out.length * 8; i++) {
    const byteIdx = i >>> 3;
    out[byteIdx] = (out[byteIdx]! & 0xFE) | allBits[i]!;
  }
  return out;
}

/** Extract a length-prefixed payload from LSB-embedded pixel data. */
export function extractImageLsb(carrier: Uint8Array): Uint8Array {
  const bits: number[] = [];
  for (let i = 0; i < carrier.length * 8; i++) {
    bits.push(carrier[i >>> 3]! >> (i & 7) & 1);
  }
  // Read 4-byte big-endian length.
  let payloadLen = 0;
  for (let i = 0; i < 32; i++) {
    payloadLen = (payloadLen << 1) | (bits[i] ?? 0);
  }
  if (payloadLen <= 0 || payloadLen > (bits.length - 32) / 8) {
    return new Uint8Array(0); // no valid payload
  }
  const payloadBytes = new Uint8Array(payloadLen);
  for (let i = 0; i < payloadLen * 8 && 32 + i < bits.length; i++) {
    const byteIdx = i >>> 3;
    payloadBytes[byteIdx] = (payloadBytes[byteIdx]! << 1) | (bits[32 + i]! & 1);
  }
  return payloadBytes;
}

function bitsFromBytes(data: Uint8Array): number[] {
  const bits: number[] = [];
  for (const byte of data) {
    for (let b = 7; b >= 0; b--) bits.push((byte >> b) & 1);
  }
  return bits;
}

// ------------------------------------------------------------------------- //
// BMP 24-bit carrier generation (seeded noise + LSB embed)
// ------------------------------------------------------------------------- //

/** Mulberry32 PRNG for deterministic pixel noise. */
function mulberry32(seed: number): () => number {
  let s = seed | 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Generate a 24-bit BMP with the command embedded via LSB.
 *  Returns the complete BMP file bytes (Buffer). */
export function generateC2Image(command: string, width = 32, height = 32, seed = 0x56414e5441): Buffer {
  const payload = Buffer.from(command, "utf-8");
  const rowSize = ((width * 3 + 3) >>> 2) << 2;
  const pixelDataSize = rowSize * height;
  const fileSize = 54 + pixelDataSize;

  // BMP header (14) + DIB header (40)
  const header = Buffer.alloc(54);
  header.write("BM", 0);
  header.writeUInt32LE(fileSize, 2);
  header.writeUInt32LE(54, 10); // data offset

  // DIB header
  header.writeUInt32LE(40, 14); // header size
  header.writeInt32LE(width, 18);
  header.writeInt32LE(height, 24); // positive = bottom-up
  header.writeUInt16LE(1, 26);    // planes
  header.writeUInt16LE(24, 28);   // bpp
  header.writeUInt32LE(0, 30);    // no compression
  header.writeUInt32LE(pixelDataSize, 34);

  // Pixel data (bottom-up BGR rows, padded)
  const pixels = Buffer.alloc(pixelDataSize);
  const rng = mulberry32(seed);

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const b = Math.floor(rng() * 256);
      const g = Math.floor(rng() * 256);
      const r = Math.floor(rng() * 256);
      const rowStart = (height - 1 - y) * rowSize + x * 3;
      pixels[rowStart] = b;
      pixels[rowStart + 1] = g;
      pixels[rowStart + 2] = r;
    }
  }

  // Embed the payload into the pixel data.
  const embedded = embedImageLsb(pixels, payload);

  return Buffer.concat([header, embedded]);
}

/** Extract the command from a BMP file generated by generateC2Image. */
export function extractC2Image(bmpBytes: Uint8Array): { status: string; command?: string; payloadSize?: number; note?: string } {
  if (bmpBytes.length < 54) return { status: "no-payload", note: "too small" };
  const dv = new DataView(bmpBytes.buffer, bmpBytes.byteOffset, bmpBytes.byteLength);
  const bpp = dv.getUint16(28, true);
  if (bpp !== 24) return { status: "no-payload", note: `unsupported bpp ${bpp}` };
  const width = dv.getInt32(18, true);
  const height = dv.getInt32(24, true);
  const absHeight = height < 0 ? -height : height;
  const rowSize = ((width * 3 + 3) >>> 2) << 2;
  const pixelData = bmpBytes.subarray(54, 54 + rowSize * absHeight);
  const payload = extractImageLsb(pixelData);
  if (!payload.length) return { status: "no-payload", note: "no valid payload found" };
  return { status: "extracted", command: Buffer.from(payload).toString("utf-8"), payloadSize: payload.length };
}

/** LSB-plane analysis of a 24-bit BMP (stego detection heuristic). */
export function detectStego(bmpBytes: Uint8Array): Record<string, unknown> {
  const dv = new DataView(bmpBytes.buffer, bmpBytes.byteOffset, bmpBytes.byteLength);
  if (bmpBytes.length < 54) return { file: "(buffer)", error: "too small" };
  const bpp = dv.getUint16(28, true);
  if (bpp !== 24) return { file: "(buffer)", note: `unsupported bpp ${bpp}` };
  const width = dv.getInt32(18, true);
  const height = dv.getInt32(24, true);
  const absHeight = height < 0 ? -height : height;
  const rowSize = ((width * 3 + 3) >>> 2) << 2;
  const pixelData = bmpBytes.subarray(54, 54 + rowSize * absHeight);

  const counts: { R: [number, number]; G: [number, number]; B: [number, number] } = { R: [0, 0], G: [0, 0], B: [0, 0] };
  for (let i = 0; i < pixelData.length; i += 3) {
    const b = pixelData[i];
    const g = pixelData[i + 1];
    const r = pixelData[i + 2];
    if (b === undefined || g === undefined || r === undefined) break;
    counts.B[b & 1] = (counts.B[b & 1] ?? 0) + 1;
    counts.G[g & 1] = (counts.G[g & 1] ?? 0) + 1;
    counts.R[r & 1] = (counts.R[r & 1] ?? 0) + 1;
  }

  const planes: Record<string, unknown> = {};
  const flags: string[] = [];
  for (const ch of ["R", "G", "B"]) {
    const pair = counts[ch as keyof typeof counts];
    const zeros = pair[0];
    const ones = pair[1];
    const total = (zeros ?? 0) + (ones ?? 0) || 1;
    const ratio = ones / total;
    planes[ch] = { zeros, ones, ones_ratio: Math.round(ratio * 10000) / 10000 };
    if (!Number.isNaN(ratio) && ratio >= 0.45 && ratio <= 0.55) {
      flags.push(`${ch}: near-uniform LSB distribution (possible randomization)`);
    }
  }

  return {
    planes,
    indicators: flags.length ? flags : ["no obvious LSB randomization detected"],
    note: "uniform LSB planes are a weak stego indicator; histogram/chi-square follow-ups advised",
  };
}

// ------------------------------------------------------------------------- //
// Algorithm / carrier catalogs (advisory — ported from Python)
// ------------------------------------------------------------------------- //

export interface StegoAlgorithm {
  name: string;
  description: string;
  quality: number;
  capacity: number;
  detectionRisk: string;
}

export interface CarrierFormat {
  name: string;
  maxSizeMB: number;
  detectionRisk: string;
  bestAlgorithms: string[];
}

export const STEGO_ALGORITHMS: Record<string, StegoAlgorithm> = {
  lsb: { name: "Least Significant Bit", description: "Embed data in LSBs of pixels", quality: 95, capacity: 0.125, detectionRisk: "low" },
  dct: { name: "Discrete Cosine Transform", description: "Embed data in DCT coefficients", quality: 90, capacity: 0.1, detectionRisk: "medium" },
  spread_spectrum: { name: "Spread Spectrum", description: "Spread data across frequency domain", quality: 85, capacity: 0.05, detectionRisk: "very_low" },
  palette: { name: "Palette-Based", description: "Embed data in palette index values", quality: 100, capacity: 0.0625, detectionRisk: "low" },
};

export const CARRIER_FORMATS: Record<string, CarrierFormat> = {
  png: { name: "PNG Image", maxSizeMB: 50, detectionRisk: "low", bestAlgorithms: ["lsb", "dct"] },
  bmp: { name: "BMP Image", maxSizeMB: 100, detectionRisk: "medium", bestAlgorithms: ["lsb", "palette"] },
  jpg: { name: "JPEG Image", maxSizeMB: 100, detectionRisk: "low", bestAlgorithms: ["dct", "spread_spectrum"] },
  wav: { name: "WAV Audio", maxSizeMB: 50, detectionRisk: "low", bestAlgorithms: ["lsb", "spread_spectrum"] },
  mp4: { name: "MP4 Video", maxSizeMB: 100, detectionRisk: "low", bestAlgorithms: ["spread_spectrum"] },
};