
import { runSelfImprovement } from "../src/ares/self_improvement.ts";
import * as fs from "node:fs";
import * as path from "node:path";

async function testIngestion() {
  console.log("🚀 Testing ARES v2.3 Autonomous Ingestor...");
  
  const techId = "LOTAPI_NOTION_C2";
  const payloadCode = `
/**
 * Synthesized LotAPI C2 module for Notion.
 * Generated by ARES v2.3 Autonomous Ingestor.
 */
import { moduleEnvelope } from "./module_helpers.ts";

export async function runLotapiNotionC2(req: any, opts: any = {}) {
  return moduleEnvelope(opts.dryRun !== false, {
    status: "active",
    channel: "notion_api",
    summary: "Covert C2 signaling active via Notion block comments."
  });
}
`;

  console.log(`[+] Triggering ingestion for ${techId}...`);
  const result = await runSelfImprovement({
    techniqueId: techId,
    payloadCode: payloadCode,
    testCommand: "node -e 'console.log(\"LIVE_PROVEN\")'"
  }, { live: true });

  console.log(`[+] Ingestion result: ${result.data.summary}`);
  
  const artifactPath = result.data.validation.artifactPath;
  if (artifactPath && fs.existsSync(artifactPath)) {
    console.log(`[SUCCESS] Artifact created at: ${artifactPath}`);
    
    // Check if registry update is needed manually or via script
    console.log("[!] Registry update requires manual verify or mutation script execution.");
  } else {
    console.log("[FAILURE] Artifact not created.");
    process.exit(1);
  }
}

testIngestion().catch(err => {
  console.error(err);
  process.exit(1);
});
